### ISSUE TITLE
[BUG]- dmtx4kz302c throws exception upon registering

### ISSUE THREAD

**Issue by alex-johnson** [PepperDash/Essentials#155]
Register of device dmtx4kz302c on a dmMd16x16 (non 3 series) throws an exception. 
I believe this is an issue in the Crestron library, but bringing it up just in case.

Running v1.5.1-hotfix-174

```
[16:48:51.579]App 1:[dmTx-6] Activating
[16:48:51.594]App 1:[dmTx-6] ERROR: Device Activation failure:
System.InvalidOperationException: Attempt to read UShortValue of NullSig
   at Crestron.SimplSharpPro.Sig.get_UShortValue()
   at Crestron.SimplSharpPro.DM.Endpoints.Transmitters.DmTx4kX02CBase.get_AudioSourceFeedback()
   at PepperDash.Essentials.DM.DmTx4kz302CController.<.ctor>b__5()
   at PepperDash.Essentials.Core.IntFeedback.FireUpdate()
   at PepperDash.Essentials.Core.CrestronGenericBaseDevice.CustomActivate()
   at PepperDash.Essentials.DM.DmTx4kz302CController.CustomActivate()
   at PepperDash.Core.Device.Activate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.InitializeSystem()
   at Crestron.SimplSharpPro.CrestronControlSystem.InitializeSimplSharpProApplication()
   at Crestron.SimplSharpProInternal.SimplSharpProManager.LoadSimplSharpProApplication(String moduleFileName)
   at Crestron.SimplSharpProInternal.SimplSharpProManager..ctor(UInt32 appNumber, String simplSharpProAppName, UInt32 flags, Boolean& badExit)
   at Crestron.SimplSharpProEntry.b(String[] A_0)
```

Config entry here:
`  
          {
                "key": "dmTx-6",
                "uid": 2,
                "name": "Input 6 DM-TX",
                "type": "dmtx4kz302c",
                "group": "dmEndpoint",
                "properties": {
                    "control": {
                        "method": "ipid",
                        "ipid": "C6",
                        "params": {
                            "endOfLineString": "\n",
                            "deviceReadyResponsePattern": ".*>"
                        }
                    },
                    "parentDeviceKey": "dmMd16x16-1",
                    "parentInputNumber": 6
                }
            },
`

**Comment by andrew-welker** [comment]
Not necessarily. The XML comments for that Sig (DmTx4kX02Base.AudioSourceFeedback) state that it's only valid for the DM-TX-4K-202-C and DM-TX-4K-302-C. I'll change that property to return the same value as the VideoSourceFeedback instead.

**Comment by alex-johnson** [comment]
Ha - I read that note too and thought well this is a 302. Too many product names.
