### ISSUE TITLE
[BUG]-DM Chassis Bridge throws NullReference with Dm-Tx-4k-100-c-1g

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#240]
**Describe the bug**
A null reference exception is thrown when bridging to a DM Chassis with a DM-TX-4K-100-C-1G

**Stacktrace**

```
[12:31:46.000]App 4:Creating Tx Feedbacks 2
[12:31:46.000]App 4:[DmChassisBridge] ERROR: Device PostActivation failure:
System.NullReferenceException: NullReferenceException
   at PepperDash.Essentials.DM.DmChassisController.LinkToApi(BasicTriList trilist, UInt32 joinStart, String joinMapKey, EiscApiAdvanced bridge)
   at PepperDash.Essentials.Core.Bridges.EiscApiAdvanced.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**Additional context**
Config below (some values changed to conceal sensitive client info):

```json
{
                "key": "DmChassis",
                "uid": 1,
                "name": "DM-MD8x8 CPU3",
                "type": "dmmd8x8cpu3",
                "group": "dmChassis",
                "properties": {
                    "control": {
                        "method": "ipid",
                        "ipid": "40",
                        "params": {
                            "endOfLineString": "\n",
                            "deviceReadyResponsePattern": ".*>"
                        }
                    },
                    "volumeControls": {},
                    "inputSlotSupportsHdcp2": {
                        "1": true,
                        "2": true,
                        "3": true
                    },
                    "noRouteText": "No Source",
                    "inputSlots": {
                        "1": "dmc4kzC",
                        "2": "dmc4kzHd",
                        "3": "dmc4kzHd",
                        "4": "",
                        "5": "dmcSdi",
                        "6": "dmcSdi",
                        "7": "",
                        "8": ""
                    },
                    "outputSlots": {
                        "1": "dmc4kzCoHd",
                        "2": "dmc4kzCoHd",
                        "3": "dmc4kHdo",
                        "4": "dmc4kHdo"
                    },
                    "inputNames": {
                        "1": "PC",
                        "2": "Laptop",
                        "3": "-",
                        "5": "Wireless",
                        "6": "",
                        "7": "",
                        "8": "-"
                    },
                    "outputNames": {
                        "1": "Projector Left",
                        "2": "-",
                        "3": "Projector Right",
                        "4": "",
                        "5": "-",
                        "6": "",
                        "7": "-",
                        "8": "-"
                    },
                    "parentDeviceKey": "processor"
                }
            },
            {
                "key": "DmChassisBridge",
                "uid": 4,
                "name": "eiscBridge DMSwitch",
                "group": "api",
                "type": "eiscApiAdvanced",
                "properties": {
                    "control": {
                        "tcpSshProperties": {
                            "address": "127.0.0.2",
                            "port": 0
                        },
                        "ipid": "D0",
                        "method": "ipidTcp"
                    },
                    "devices": [
                        {
                            "deviceKey": "DmChassis",
                            "joinStart": 1
                        }
                    ]
                }
            },
            {
                "key": "DmScaler01",
                "uid": 5,
                "name": "Left Display Rx",
                "type": "dmRmc4kz100C",
                "group": "dmEndpoint",
                "properties": {
                    "control": {
                        "method": "ipid",
                        "ipid": "51",
                        "params": {
                            "endOfLineString": "\n",
                            "deviceReadyResponsePattern": ".*>"
                        }
                    },
                    "parentDeviceKey": "dmChassis",
                    "parentOutputNumber": 1
                }
            },
            {
                "key": "DmScaler02",
                "uid": 5,
                "name": "Right Display Rx",
                "type": "dmRmc4kz100C",
                "group": "dmEndpoint",
                "properties": {
                    "control": {
                        "method": "ipid",
                        "ipid": "52",
                        "params": {
                            "endOfLineString": "\n",
                            "deviceReadyResponsePattern": ".*>"
                        }
                    },
                    "parentDeviceKey": "dmChassis",
                    "parentOutputNumber": 2
                }
            },
            {
                "key": "DmTx01",
                "uid": 5,
                "name": "Laptop Tx",
                "type": "dmtx4k100c1g",
                "group": "dmEndpoint",
                "properties": {
                    "control": {
                        "method": "ipid",
                        "ipid": "41",
                        "params": {
                            "endOfLineString": "\n",
                            "deviceReadyResponsePattern": ".*>"
                        }
                    },
                    "parentDeviceKey": "dmChassis",
                    "parentInputNumber": 2
                }
            }
```

**Comment by ngenovese11** [comment]
```
Friendly Name             : PepperDashEssentials 
Application Name          : PepperDashEssentials 
Program File              : PepperDashEssentials.dll 
Min Firmware Version      : 1.009.0029 
Program Tool              : SIMPL# Plugin 
Design Tool ID            : 5 
Program Tool ID           : 5 
Archive Name              :  
Compiled On               : 6/2/2020 2:45:52 PM 
Compiler Revision         : 1.5.5.26575 
PlugInVersion             : 2.0.58.0 
Include4.dat              : 2.12.040 
```
