### ISSUE TITLE
[BUG]-Latest development version (1.5.6-beta-339) missingMethod exception when linking bridges 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#258]
**Describe the bug**
Same plugins work fine in version 1.5.4 

**Stacktrace**

Include a stack trace of the exception if possible.
```

[08:20:11.000]App 2:[Cameras-Bridge] ERROR: Device PostActivation failure:
System.MissingMethodException: MissingMethodException
   at PepperDash.Essentials.Bridges.EiscApi.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()


   [08:20:09.000]App 2:[eisc-Dsp] ERROR: Device PostActivation failure:
System.MissingMethodException: MissingMethodException
   at PepperDash.Essentials.Bridges.EiscApi.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()\


   [08:20:11.000]App 2:[EfS-MiscDevice-Local-Bridge] ERROR: Device PostActivation failure:
System.MissingMethodException: MissingMethodException
   at PepperDash.Essentials.Bridges.EiscApi.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**To Reproduce**
Talk to @jtalborough for client source code.

**Comment by andrew-welker** [comment]
This issue is related/because of #237. See that issue for continuing conversation.
