### ISSUE TITLE
[BUG]-1.5.6 - Generic Relay Class throws NullReferenceException in Bridge

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#282]
**Describe the bug**
LinkToApi in the Generic Relay Class throws a null reference when bridged from an EiscAdvanced.  Confirmed no error in 1.5.5

**Stacktrace**
```
[07:18:41.000]App 2:[RelayBridge] ERROR: Device PostActivation failure:
System.NullReferenceException: NullReferenceException
   at PepperDash.Essentials.Core.CrestronIO.GenericRelayDevice.LinkToApi(BasicTriList trilist, UInt32 joinStart, String joinMapKey, EiscApiAdvanced bridge)
   at PepperDash.Essentials.Core.Bridges.EiscApiAdvanced.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**To Reproduce**
```
{
                "key": "LeftScreenUpRelay",
                "uid": 1,
                "name": "LeftScreenUpRelay",
                "group": "io",
                "type": "relayoutput",
                "properties": {
                    "portDeviceKey": "processor",
                    "portNumber": 5
                }
            },
            {
                "key": "LeftScreenDownRelay",
                "uid": 1,
                "name": "LeftScreenDownRelay",
                "group": "io",
                "type": "relayoutput",
                "properties": {
                    "portDeviceKey": "processor",
                    "portNumber": 6
                }
            },
            {
                "key": "CenterScreenUpRelay",
                "uid": 1,
                "name": "CenterScreenUpRelay",
                "group": "io",
                "type": "relayoutput",
                "properties": {
                    "portDeviceKey": "processor",
                    "portNumber": 1
                }
            },
            {
                "key": "CenterScreenDownRelay",
                "uid": 1,
                "name": "CenterScreenDownRelay",
                "group": "io",
                "type": "relayoutput",
                "properties": {
                    "portDeviceKey": "processor",
                    "portNumber": 2
                }
            },
            {
                "key": "RightScreenUpRelay",
                "uid": 1,
                "name": "RightScreenUpRelay",
                "group": "io",
                "type": "relayoutput",
                "properties": {
                    "portDeviceKey": "processor",
                    "portNumber": 3
                }
            },
            {
                "key": "RightScreenDownRelay",
                "uid": 1,
                "name": "RightScreenDownRelay",
                "group": "io",
                "type": "relayoutput",
                "properties": {
                    "portDeviceKey": "processor",
                    "portNumber": 4
                }
            },
            {
                "key": "RelayBridge",
                "uid": 13422,
                "name": "RelayBridge",
                "group": "api",
                "type": "eiscApiAdvanced",
                "properties": {
                    "control": {
                        "tcpSshProperties": {
                            "address": "127.0.0.2",
                            "port": 0
                        },
                        "ipid": "Db",
                        "method": "ipidTcp"
                    },
                    "devices": [  
                        {
                            "deviceKey": "LeftScreenUpRelay",
                            "joinStart": 1
                        },
                        {
                            "deviceKey": "LeftScreenDownRelay",
                            "joinStart": 2
                        },
                        {
                            "deviceKey": "CenterScreenUpRelay",
                            "joinStart": 3
                        },
                        {
                            "deviceKey": "CenterScreenDownRelay",
                            "joinStart": 4
                        },
                        {
                            "deviceKey": "RightScreenUpRelay",
                            "joinStart": 5
                        },
                        {
                            "deviceKey": "RightScreenDownRelay",
                            "joinStart": 6
                        }
                    ]
                }
            }
```

**Comment by andrew-welker** [comment]
What processor model was Essentials running on when you hit this error?

**Comment by ngenovese11** [comment]
This might help:

```
{
                "key": "processor",
                "type": "pro3",
                "name": "PRO3",
                "group": "processor",
                "supportedConfigModes": [
                    "compliance",
                    "essentials"
                ],
                "supportedSystemTypes": [
                    "hudType",
                    "presType",
                    "vtcType",
                    "custom"
                ],
                "supportsCompliance": true,
                "properties": {
                    "numberOfComPorts": 6,
                    "numberOfIrPorts": 8,
                    "numberOfRelays": 8,
                    "numberOfDIOPorts": 8
                }
            }
```

**Comment by andrew-welker** [comment]
Config doesn't necessarily have to match the actual processor that the program is running on. However, I think that was a red herring, as I'm running on my RMC3 and hitting the same issue. Investigating further.

**Comment by ngenovese11** [comment]
I can also confirm its on a PRO3 on site.

Nick Genovese
Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required

**Comment by andrew-welker** [comment]
I think I've found the issue. Testing locally, then I'll have a build for you to test as well.

**Comment by andrew-welker** [comment]
The issue was that the `OutputIsOnFeedback` was not being initialized in the constructor that the GenericRelayDevice factory was using. I've corrected that and tested locally. I'll get you a hotfix build shortly. Do you need a full release for your customer?

**Comment by ngenovese11** [comment]
1.5.5 is stable for me so no immediate release needed
