### ISSUE TITLE
[BUG]-Internal Essentials Join Maps can't be inherited and extended

### ISSUE THREAD

**Issue by andrew-welker** [PepperDash/Essentials#323]
**Describe the bug**
When join maps in plugins inherit from any of the existing internal join maps, an `InvalidCastException` is thrown when the `AddJoins` method in `JoinMapBaseAdvanced` class. This is probably due to the attempt to cast to the parent class in the AddJoins method.
**Stacktrace**
```
System.InvalidCastException: Object must implement IConvertible.ailure:
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at PepperDash.Essentials.Core.JoinMapBaseAdvanced.AddJoins(Type type)
   at PepperDash.Essentials.Core.JoinMapBaseAdvanced..ctor(UInt32 joinStart, Type type)
   at PepperDash.Essentials.Core.Bridges.DmChassisControllerJoinMap..ctor(UInt32 joinStart)
   at EssentialsPluginTemplateEPI.EssentialsPluginBridgeJoinMapTemplate..ctor(UInt32 joinStart)
   at EssentialsPluginTemplateEPI.EssentialsPluginDeviceTemplate.LinkToApi(BasicTriList trilist, UInt32 joinStart, String joinMapKey, EiscApiAdvanced bridge)
   at PepperDash.Essentials.Core.Bridges.EiscApiAdvanced.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**Expected behavior**
It should be possible to inherit existing join maps without exceptions being thrown.

**Screenshots**

**Additional context**
As a workaround, it is possible to add an existing join map as a public property and access it's data and have it added to the internal `Joins` dictionary for the console command. This isn't really ideal though.

**Comment by andrew-welker** [comment]
@ndorin proposed a solution. The proposed solution is to make the constructors in the internal Essentials join maps that are used by Essentials devices be internal, and add a public one that the inheriting classes can use that will set the type correctly.
