### ISSUE TITLE
[BUG]-Plugin Creating Generic Type Exception

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#359]
**Describe the bug**
On initial loads of a program with plugins, it appears to function as normal.  On subsequent restarts, however, `System.NotSupportedException: GetMethods for Open Generic Types is not supported` - I'm guessing it has to do with what happens when you load a plugin from the `loadedAssemblies` directory.

To my knowledge - it doesn't appear to cause any issues - and the plugin functions as normal 

**Stacktrace**

Include a stack trace of the exception if possible.
```
[10:35:04.000]App 1:Load Plugin not found. Tesira-DSP-EPI.<>f__AnonymousType0`2 is not a plugin factory. Exception: System.NotSupportedException: GetMethods for Open Generic Types is not supported.
   at System.RuntimeType.GetMethods(BindingFlags bindingAttr)
   at Crestron.SimplSharp.Reflection.CTypeImpl.GetMethods(BindingFlags bindingAttr)
   at PepperDash.Essentials.PluginLoader.LoadCustomPluginTypes()
   at PepperDash.Essentials.PluginLoader.LoadPlugins()
   at PepperDash.Essentials.ControlSystem.GoWithLoad(Object notUsed)
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()

[10:35:04.000]App 1:Load Plugin not found. Tesira-DSP-EPI.<>f__AnonymousType1`2 is not a plugin factory. Exception: System.NotSupportedException: GetMethods for Open Generic Types is not supported.
   at System.RuntimeType.GetMethods(BindingFlags bindingAttr)
   at Crestron.SimplSharp.Reflection.CTypeImpl.GetMethods(BindingFlags bindingAttr)
   at PepperDash.Essentials.PluginLoader.LoadCustomPluginTypes()
   at PepperDash.Essentials.PluginLoader.LoadPlugins()
   at PepperDash.Essentials.ControlSystem.GoWithLoad(Object notUsed)
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()

[10:35:04.000]App 1:Load Plugin not found. Tesira-DSP-EPI.<>f__AnonymousType2`2 is not a plugin factory. Exception: System.NotSupportedException: GetMethods for Open Generic Types is not supported.
   at System.RuntimeType.GetMethods(BindingFlags bindingAttr)
   at Crestron.SimplSharp.Reflection.CTypeImpl.GetMethods(BindingFlags bindingAttr)
   at PepperDash.Essentials.PluginLoader.LoadCustomPluginTypes()
   at PepperDash.Essentials.PluginLoader.LoadPlugins()
   at PepperDash.Essentials.ControlSystem.GoWithLoad(Object notUsed)
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()

[10:35:04.000]App 1:Load Plugin not found. Tesira-DSP-EPI.<>f__AnonymousType3`2 is not a plugin factory. Exception: System.NotSupportedException: GetMethods for Open Generic Types is not supported.
   at System.RuntimeType.GetMethods(BindingFlags bindingAttr)
   at Crestron.SimplSharp.Reflection.CTypeImpl.GetMethods(BindingFlags bindingAttr)
   at PepperDash.Essentials.PluginLoader.LoadCustomPluginTypes()
   at PepperDash.Essentials.PluginLoader.LoadPlugins()
   at PepperDash.Essentials.ControlSystem.GoWithLoad(Object notUsed)
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**To Reproduce**
1. Load a plugin
2. Restart a program so that the plugin loads from `loadedAssemblies`

**Expected behavior**
A clean startup sequence without exceptions

**Additional context**
The plugin for which this error occurs has multiple EssentialsBridgeableDevices, but only one of them has a factory method - could this be the cause of the exception?

**Comment by andrew-welker** [comment]
This exception only appears when `APPDEBUG`  is set to 2, and is a result of the old plugin loading process. Once the old plugin loading process is removed, this exception won't appear under any circumstances.
