### ISSUE TITLE
[BUG]-Deprecate LutronQuantum Deivce and point support to plugin. 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#422]
**Describe the bug**
The Lutron Quantum is present in Essentials Core but functionality has been moved to a plugin. The EiscBridge is currently not functioning correctly and tosses an exception when selecting scenes via digital input. 

**Stacktrace**

Include a stack trace of the exception if possible.
```
[12:52:23.000]App 2:[EnviormentBridge] Error in Eisc_SigChange handler: System.ArgumentOutOfRangeException:
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PepperDash.Essentials.Core.Lighting.LightingBase.<>c__DisplayClass6.<LinkLightingToApi>b__3(UInt16 u)
   at PepperDash.Essentials.Core.Bridges.EiscApiAdvanced.Eisc_SigChange(Object currentDevice, SigEventArgs args)
   at Crestron.SimplSharpPro.DeviceSupport.BasicTriList.g(CrestronDevice A_0, SigEventArgs A_1)
   at Crestron.SimplSharpPro.CrestronDeviceWithEvents.SendJoinEventData(SigEventArgs args)
   at Crestron.SimplSharpPro.SigCollectionBase`1.NotifyOfSigsNewValue(UShortOutputSig paramSig, eSigEvent paramSigEvent, Boolean paramSigWasAdded)
   at Crestron.SimplSharpPro.DeviceUShortOutputCollection.UpdateValueWithOutIncrementWithEvent(UInt32 index, UInt16 newValue)
   at Crestron.SimplSharpPro.DeviceUShortOutputCollection.UpdateValueWithEvent(UInt32 index, UInt16 newValue)
   at Crestron.SimplSharpProInternal.DeviceBasis.ReadAnalogPacket(UInt32 joinNumber, UInt16 joinValue)
   at Crestron.SimplSharpProInternal.CrestronDevice.HandleIncomingBufferForSpecificDevice(CParsedPacketData IncomingDataStructure)
   at Crestron.SimplSharpProInternal.DeviceBasis.ParseProcessedCresnetData(CParsedPacketData IncomingDataStructure)
   at Crestron.SimplSharpProInternal.CrestronDevice.ParseDataFromStructure(Byte* pIncomingDataBuffer, UInt32 tldmToAppDeviceOrSlotId)
   at Crestron.SimplSharpProInternal.CrestronDevice.CallbackRoutineForSpecificDevice()
```

**Comment by ndorin** [comment]
Plugin would need to be made public first.

Sent from my iPhone

On Sep 17, 2020, at 11:13 AM, Jason T Alborough <notifications@github.com> wrote:

﻿

Describe the bug
The Lutron Quantum is present in Essentials Core but functionality has been moved to a plugin. The EiscBridge is currently not functioning correctly and tosses an exception when selecting scenes via digital input.

Stacktrace

Include a stack trace of the exception if possible.

[12:52:23.000]App 2:[EnviormentBridge] Error in Eisc_SigChange handler: System.ArgumentOutOfRangeException:
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PepperDash.Essentials.Core.Lighting.LightingBase.<>c__DisplayClass6.<LinkLightingToApi>b__3(UInt16 u)
   at PepperDash.Essentials.Core.Bridges.EiscApiAdvanced.Eisc_SigChange(Object currentDevice, SigEventArgs args)
   at Crestron.SimplSharpPro.DeviceSupport.BasicTriList.g(CrestronDevice A_0, SigEventArgs A_1)
   at Crestron.SimplSharpPro.CrestronDeviceWithEvents.SendJoinEventData(SigEventArgs args)
   at Crestron.SimplSharpPro.SigCollectionBase`1.NotifyOfSigsNewValue(UShortOutputSig paramSig, eSigEvent paramSigEvent, Boolean paramSigWasAdded)
   at Crestron.SimplSharpPro.DeviceUShortOutputCollection.UpdateValueWithOutIncrementWithEvent(UInt32 index, UInt16 newValue)
   at Crestron.SimplSharpPro.DeviceUShortOutputCollection.UpdateValueWithEvent(UInt32 index, UInt16 newValue)
   at Crestron.SimplSharpProInternal.DeviceBasis.ReadAnalogPacket(UInt32 joinNumber, UInt16 joinValue)
   at Crestron.SimplSharpProInternal.CrestronDevice.HandleIncomingBufferForSpecificDevice(CParsedPacketData IncomingDataStructure)
   at Crestron.SimplSharpProInternal.DeviceBasis.ParseProcessedCresnetData(CParsedPacketData IncomingDataStructure)
   at Crestron.SimplSharpProInternal.CrestronDevice.ParseDataFromStructure(Byte* pIncomingDataBuffer, UInt32 tldmToAppDeviceOrSlotId)
   at Crestron.SimplSharpProInternal.CrestronDevice.CallbackRoutineForSpecificDevice()

**Comment by jtalborough** [comment]
Thats fine.
https://github.com/PepperDash-Engineering/epi-lighting-lutron_quantum/blob/main/PDT.LutronQuantum.EPI/LutronQuantum.cs

**Comment by andrew-welker** [comment]
@jtalborough if that plug-in supports nuget, let me know and I'll get the ownership transferred to the correct org so it can be public.

**Comment by andrew-welker** [comment]
@jtalborough Has the Lutron plugin been made public yet?

**Comment by jtalborough** [comment]
No not to my knowledge.

**Comment by jtalborough** [comment]
Lutron is moved over, deprecate lutron implementation in essentials.
