### ISSUE TITLE
[BUG]-The c2nrths device registration can fail under certain conditions and cause cascading issues with device registration 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#435]
**Describe the bug**
I was not able to pull this all the way apart but from what I can tell the c2nrths registration was failing...which was in turn causing other device registration failures. Simply removing the c2nrths we get all subsequent device registrations working properly. Stack trace below. Contact me for full plugin stack and config. 

**Stacktrace**

Include a stack trace of the exception if possible.
```
440. Error: TLDM.exe # 2020-10-01 17:32:47  # CRM: re-registering a permenant device 2a
441. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:32:57  #  Unable to get registration response for ID-2A of DEVICE_PARENT_CRESNET_TYPE - ID 0x2A
442. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:32:57  #
443. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:32:57  # App 2:Register device result: 'TempGauge01', type 'C2N-RTHS ID-2A', result Failure
449. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:33:07  #  Unable to get registration response for IP-ID-BB of DEVICE_PARENT_ETHERNET_TYPE - ID 0xBB
450. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:33:07  #
451. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:33:07  # App 2:[] Registration result: Failure
452. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:33:18  #  Unable to get registration response for IP-ID-ED of DEVICE_PARENT_ETHERNET_TYPE - ID 0xED
453. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:33:18  #
454. Error: SimplSharpPro.exe [App 2] # 2020-10-01 17:33:18  # App 2:[DisplayBridge] Registration result: Failure
455. Error: TLDM.exe # 2020-10-01 17:33:27  #  CTHALCresnetDriverInterface: Timed out waiting for IOP response
456. Error: TLDM.exe # 2020-10-01 17:33:27  #  CTHALCresnetDriverInterface - Unable to SendDeviceRegisterMessage to the IO Processor
457. Error: TLDM.exe # 2020-10-01 17:33:27  #  Cresnet Id 0x2a. Device Registration Failed. Error code 0x102
458. Error: CIPCommandProcessor.exe # 2020-10-01 17:33:27  # Exception: HeartBeatMsgHandler - System.InvalidOperationException: InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.SortedList`2.Enumerator.MoveNext()
   at C459. Error: CIPCommandProcessor.exe # 2020-10-01 17:33:27  # IPHeartBeatMsgHandler.SendTCPClientHeartbeatMessage()
   at CIPHeartBeatMsgHandler.HeartBeatMsgHandler()
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TrevorPayne** [comment]
Bump - @jtalborough - I'm interested if you've seen this issue again.  I use this on multiple projects and have never experienced this.

**Comment by jtalborough** [comment]
I probably have not seen the device in the last three years...if your using c2nrths without issue we can call it closed.
