### ISSUE TITLE
[BUG]-DisplayBase throws missing method Exception

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#521]
**Describe the bug**
Essentials - 1.6.9
A previously functioning display plugin that was inheriting from DisplayBase is no longer being bridged as a Missing Method Exception is thrown.

**Stacktrace**

Include a stack trace of the exception if possible.
```
System.MissingMethodException: Method not found: get_PowerIsOnFeedback PepperDash.Essentials.Core.DisplayBase.
   at EpsonProjectorEpi.EpsonProjector.LinkToApi(BasicTriList trilist, UInt32 joinStart, String joinMapKey, EiscApiAdvanced bridge)
   at PepperDash.Essentials.Bridges.EiscApi.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**Comment by ngenovese11** [comment]
@alex-johnson for visibility

**Comment by ngenovese11** [comment]
Additional context, this also happens in a separate plugin:

```
System.MissingMethodException: Method not found: get_PowerIsOnFeedback PepperDash.Essentials.Core.DisplayBase.
   at PDT.PanasonicDisplay.EPI.PdtPanasonicDisplay.LinkToApi(BasicTriList trilist, UInt32 joinStart, String joinMapKey)
   at PepperDash.Essentials.Bridges.EiscApi.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**Comment by alex-johnson** [comment]
Recompile of the plugins with updated references appears to have resolved the issue. No action needed?

**Comment by ngenovese11** [comment]
OK if you recompile with new essentials, does it break it for older versions?

**Comment by alex-johnson** [comment]
It seems okay on earlier versions after the recompile. Tested on v1.6.4

**Comment by ngenovese11** [comment]
OK, not sure the path forward.

**Comment by andrew-welker** [comment]
In 1.6.7 and later versions, the `IPower` interface is marked obsolete and has been replaced by 2 interfaces: `IHasPowerControl` and `IHasPowerControlWithFeedback`. `IHasPowerControl` is implemented on `DisplayBase` and `IHasPowerControlWithFeedback` is implemented on `TwoWayDisplayBase`.

Updating the references for the plugins to 1.6.7 or later should resolve the issue, as the `PowerIsOnFeedback` property has moved to `TwoWayDisplayBase`, so even when running the plugin with older versions of Essentials, it should still work because of the inheritance chain.

**Comment by andrew-welker** [comment]
After talking with @alex-johnson , updating the references on the plugins to 1.6.7 or later has solved the issue. I'll close this issue.

**Comment by ngenovese11** [comment]
Should probably be noted somewhere that if you update to 1.6.9 you may need to recompile your plugins

**Comment by jtalborough** [comment]
Sounds like this is going to affect backwards compatibility. We should make sure Essentials updates will not break existing plugins.

**Comment by andrew-welker** [comment]
I've got a build for this that should restore backwards compatability. The property and implementation of `IPower` on DisplayBase WILL BE removed in version 2.0.0. Check version 1.6.9-hotfix-954 and report back on results.

**Comment by andrew-welker** [comment]
@jtalborough @alex-johnson @ngenovese11 Has anyone had a chance to check version 1.6.9-hotfix-954?

**Comment by jtalborough** [comment]
It looks like this issue persists in 1.6.9 and 1.7.0-rc-1005. 


Using a previously working display plugin that calls PowerIsOnFeedback.FireUpdate() produces an exception and a system crash shown below. The missing method does appear to be gone however. 


`
[11:31:45.000]App 2:[DisplayBridge] Error in Eisc_SigChange handler: System.InvalidProgramException: InvalidProgramException
   at PDT.PlanarRpsDisplay.EPI.PlanarRpsDisplay.PowerOn()
   at PDT.PlanarRpsDisplay.EPI.PlanarRpsDisplayBridge.<>c__DisplayClassa.<LinkToApiExt>b__1()
   at PepperDash.Essentials.Core.SigAndTriListExtensions.<>c__DisplayClass1.<SetSigTrueAction>b__0(Boolean b)
   at PepperDash.Essentials.Bridges.EiscApi.Eisc_SigChange(Object currentDevice, SigEventArgs args)
   at Crestron.SimplSharpPro.DeviceSupport.BasicTriList.g(CrestronDevice A_0, SigEventArgs A_1)
   at Crestron.SimplSharpPro.CrestronDeviceWithEvents.SendJoinEventData(SigEventArgs args)
   at Crestron.SimplSharpPro.SigCollectionBase`1.NotifyOfSigsNewValue(BoolOutputSig paramSig, eSigEvent paramSigEvent, Boolean paramSigWasAdded)
   at Crestron.SimplSharpPro.DeviceBooleanOutputCollection.UpdateValueWithOutIncrementWithEvent(UInt32 index, Boolean newValue)
   at Crestron.SimplSharpPro.DeviceBooleanOutputCollection.UpdateValueWithEvent(UInt32 index, Boolean newValue)
   at Crestron.SimplSharpProInternal.DeviceBasis.ReadDigitalPacket(ePacketType incomingPacketType, UInt32 joinNumber, Boolean joinValue)
   at Crestron.SimplSharpProInternal.CrestronDevice.HandleIncomingBufferForSpecificDevice(CParsedPacketData IncomingDataStructure)
   at Crestron.SimplSharpProInternal.DeviceBasis.ParseProcessedCresnetData(CParsedPacketData IncomingDataStructure)
   at Crestron.SimplSharpProInternal.CrestronDevice.ParseDataFromStructure(Byte* pIncomingDataBuffer, UInt32 tldmToAppDeviceOrSlotId)
   at Crestron.SimplSharpProInternal.CrestronDevice.CallbackRoutineForSpecificDevice()
