### ISSUE TITLE
[BUG]-getroutingports crash on display devices (inherited from TwoWayDisplay)

### ISSUE THREAD

**Issue by batourin** [PepperDash/Essentials#536]
Command getroutingports throwe exception.

**Stacktrace**
470. Error: SimplSharpPro.exe [App 1] # 2021-01-06 15:19:31  # CustomApplicationCMDProcessorThread: NullReferenceException -    at PepperDash.Essentials.Core.DeviceManager.GetRoutingPorts(String s)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.k()

**To Reproduce**
have device inherited from TwoWayDisplay
issue  getroutingports  from console
issue getroutingports <devicekey> to narrow down to device.

**Expected behavior**
It should handle devices not implemented IRoutingInputsOutputs interface and allocated OutputPorts property, such as display devices and end devices in the routing chain.

**Additional context**
Function: public static void GetRoutingPorts(string s) in the Essentials/essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/DeviceManager.cs  accessing OutputPorts property without checking for device implemented that interface in line 365:
var outputPorts = (device as IRoutingInputsOutputs).OutputPorts;

If device is not implementing IRoutingInputsOutputs, (device as IRoutingInputsOutputs)) is null and this is effectively (null).OutputPorts...

I believe it should be:
var outputPorts = ((device as IRoutingInputsOutputs) == null)?(device as IRoutingInputsOutputs).OutputPorts:null;

**Comment by batourin** [comment]
#541
