### ISSUE TITLE
[BUG] 1.7.3 throws exception in queue

### ISSUE THREAD

**Issue by andrew-welker** [PepperDash/Essentials#574]
1.7.3 throws exception in queue:

```
System.ArgumentException:  Invalid priority .
   at Crestron.SimplSharpPro.CrestronThread.Thread.set_Priority(eThreadPriority value)
   at PepperDash_Essentials_Core.Queues.GenericQueue..ctor(String key, eThreadPriority priority)
   at PepperDash_Essentials_Core.Queues.GenericQueue..ctor(String key)
   at Epi.Display.Lg.LgDisplayController..ctor(String key, String name, LgDisplayPropertiesConfig config, IBasicCommunication comms)
   at Epi.Display.Lg.LgDisplayControllerFactory.BuildDevice(DeviceConfig dc)
   at PepperDash.Essentials.Core.DeviceFactory.GetDevice(DeviceConfig dc)
   at PepperDash.Essentials.ControlSystem.LoadDevices()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

_Originally posted by @ngenovese11 in https://github.com/PepperDash/Essentials/issues/560#issuecomment-768454318_

**Comment by andrew-welker** [comment]
see #560 for discussion on what priority to set

**Comment by andrew-welker** [comment]
@ngenovese11 Please check build 1.7.4-hotfix-1096 once it's complete to verify that this is the fix.

**Comment by ngenovese11** [comment]
k loading now

**Comment by andrew-welker** [comment]
@ngenovese11 any updates?

**Comment by ngenovese11** [comment]
just loaded it up and no exceptions
