### ISSUE TITLE
[BUG]-On latest hot fix 1.8.2-hotfix-1249 If the Join Map object is present in the config file the initial Json parsing will exception out. 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#664]
**Stacktrace**

Include a stack trace of the exception if possible.
```
  "joinMaps": [
    {
      "TempGuageJoinMap": {
        "IsOnline": 1,
        "TemperatureFormat": 1,
        "Temperature": 1,
        "Humidity": 2,
        "Name": 1
      }
    }
  ],
  "global": null
}
Newtonsoft.Json.JsonSerializationException: Cannot deserialize JSON array into type 'System.Collections.Generic.Dictionary`2[System.String,Newtonsoft.Json.Linq.JObject]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String reference)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueProperty(JsonReader reader, JsonProperty property, JsonConverter propertyConverter, Object target, Boolean gottenCurrentValue, Object currentValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateAndPopulateObject(JsonReader reader, JsonObjectContract contract, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueNonProperty(JsonReader reader, Type objectType, JsonContract contract, JsonConverter converter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at PepperDash.Essentials.Core.Config.ConfigReader.LoadConfig2()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by andrew-welker** [comment]
You have the wrong config structure.
```json
"joinMaps": [
    {
      "TempGuageJoinMap": {
        "IsOnline": 1,
        "TemperatureFormat": 1,
        "Temperature": 1,
        "Humidity": 2,
        "Name": 1
      }
    }
  ],
```
should be

```json
"joinMaps": 
    {
      "TempGuageJoinMap": {
        "IsOnline": 1,
        "TemperatureFormat": 1,
        "Temperature": 1,
        "Humidity": 2,
        "Name": 1
      }
    }
```

**Comment by jtalborough** [comment]
The same config will be parsed fine in earlier versions of Essentials. I believe even in the latest release there is no issue. 

This version (1.8.2-hotfix-1249) will not boot with that config object. Im honestly not using the JoinMap its just latent data, but the change may break existing systems without any apparent error. I think it can be handled more gracefully.

**Comment by andrew-welker** [comment]
It doesn't actually get parsed in earlier version of Essentials. There was a change to PepperDash Core in (1.0.45)[https://github.com/PepperDash/PepperDashCore/releases/tag/1.0.45] to include the `joinMaps` object in the merged config that is parsed. Additionally, the structure for the `JoinMaps` property in the `BasicConfig` class has always been a dictionary and not an array/list.
