### ISSUE TITLE
[BUG]-Stream Debug throws exception

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#674]
**Describe the bug**
When enabling stream debugging an exception is thrown

**Stacktrace**

Include a stack trace of the exception if possible.
```
PRO3>setdevicestreamdebug lights-com both

PRO3>[10:18:17.000]App 1:Saving debug settings
Error: SimplSharpPro.exe [App 1] # 2021-04-02 10:18:17  # CustomApplicationCMDProcessorThread: FormatException -    at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider providerError: SimplSharpPro.exe [App 1] # 2021-04-02 10:18:17  # , String format, Object[] args)
   at System.String.Format(String format, Object[] args)
   at PepperDash.Core.Debug.Console(UInt32 level, String format, Object[] items)
   at PepperDash.Essentials.Core.DeviceManager.SetDeviceStreamDebugging(String s)
Error: SimplSharpPro.exe [App 1] # 2021-04-02 10:18:17  #    at PepperDash.Essentials.Core.DeviceManager.<Initialize>b__3(String s)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.k()
```

**Comment by andrew-welker** [comment]
Found it. I'll get a build with the fix published shortly.

**Comment by ngenovese11** [comment]
Cool, is it in Essentials or in Core?

**Comment by andrew-welker** [comment]
Essentials. Core doesn't really have anything to do with it actually being turned on. It just provides the interfaces and the StreamDebugging classes that devices that implement `IBasicCommunicationsWithStreamDebugging` and `ISocketStatusWithStreamDebugging` implement. The console command is Essentials-only, which is where the issue is.

1.8.3-hotfix-1272 should have the fix, if you want to test it with the same command that triggered the exception.
