### ISSUE TITLE
[BUG]-SetDeviceStreamDebug throws an exception when attempting to print confirmation message to console

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#717]
**Describe the bug**
Utilizing the optional time parameter on `SetDeviceStreamDebug` excepts, the command runs correctly, but the console message to give user confirmation throws an exception due to incorrect string.Format() syntax

**Stacktrace**

Include a stack trace of the exception if possible.
```
PRO3>SetDeviceStreamDebug switcher-com both 10


PRO3>[09:49:45.000]App 1:Saving debug settings
[09:49:45.000]App 1:Unable to convert minutes or settings value.  Please use an integer value for minutes. Errro: System.FormatException: FormatException
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(String format, Object[] args)
   at PepperDash.Core.Debug.Console(UInt32 level, String format, Object[] items)
   at PepperDash.Essentials.Core.DeviceManager.SetDeviceStreamDebugging(String s)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.k()
```

**To Reproduce**
See Above Stack Trace - shows the command I sent

**Screenshots**

**Additional context**
```C#
public static void SetDeviceStreamDebugging(string s)
{
    if (String.IsNullOrEmpty(s) || s.Contains("?"))
    {
        CrestronConsole.ConsoleCommandResponse(
            @"SETDEVICESTREAMDEBUG [{deviceKey}] [OFF |TX | RX | BOTH] [timeOutInMinutes]
{deviceKey} [OFF | TX | RX | BOTH] - Device to set stream debugging on, and which setting to use
timeOutInMinutes - Set timeout for stream debugging. Default is 30 minutes");
        return;
    }

    var args = s.Split(' ');

    var deviceKey = args[0];
    var setting = args[1];

    var timeout= String.Empty;

    if (args.Length >= 3)
    {
        timeout = args[2];
    }

    var device = GetDeviceForKey(deviceKey) as IStreamDebugging;

    if (device == null)
    {
        Debug.Console(0, "Unable to get device with key: {0}", deviceKey);
        return;
    }

    eStreamDebuggingSetting debugSetting;

    try
    {
        debugSetting = (eStreamDebuggingSetting)Enum.Parse(typeof(eStreamDebuggingSetting), setting, true);
    }
    catch
    {
        Debug.Console(0, "Unable to convert setting value.  Please use off/rx/tx/both");
        return;
    }

    if (!string.IsNullOrEmpty(timeout))
    {
        try
        {
            var min = Convert.ToUInt32(timeout);

            device.StreamDebugging.SetDebuggingWithSpecificTimeout(debugSetting, min);
            Debug.Console(0, "Device: '{0}' debug level set to {1) for {2} minutes", deviceKey, debugSetting, min);

        }
        catch (Exception e)
        {
            Debug.Console(0, "Unable to convert minutes or settings value.  Please use an integer value for minutes. Errro: {0}", e);
        }
    }
    else
    {
        device.StreamDebugging.SetDebuggingWithDefaultTimeout(debugSetting);
        Debug.Console(0, "Device: '{0}' debug level set to {1} for default time (30 minutes)", deviceKey, debugSetting);
    }
}

```

**Comment by andrew-welker** [comment]
The issue is visible in the snippet you posted. The time parameter is actually being correctly parsed and set...it's just not getting printed correctly because the `Debug.Console` statement has a `)` instead of a `}`.
